#-----------------------------------------------------------
# Vivado v2018.3 (64-bit)
# SW Build 2405991 on Thu Dec  6 23:36:41 MST 2018
# IP Build 2404404 on Fri Dec  7 01:43:56 MST 2018
# Start of session at: Wed May 10 02:13:31 2023
# Process ID: 1401243
# Current directory: /home/yutong/RISC-V_SoC/vivado
# Command line: vivado
# Log file: /home/yutong/RISC-V_SoC/vivado/vivado.log
# Journal file: /home/yutong/RISC-V_SoC/vivado/vivado.jou
#-----------------------------------------------------------
start_gui
open_project /home/yutong/RISC-V_SoC/vivado/soc/soc.xpr
Scanning sources...
Finished scanning sources
INFO: [IP_Flow 19-234] Refreshing IP repositories
INFO: [IP_Flow 19-1700] Loaded user IP repository '/home/yutong/RISC-V_SoC'.
WARNING: [IP_Flow 19-3656] If you move the project, the path for repository '/home/yutong/RISC-V_SoC' may become invalid. A better location for the repository would be in a path adjacent to the project. (Current project location is '/home/yutong/RISC-V_SoC/vivado/soc'.)
INFO: [IP_Flow 19-2313] Loaded Vivado IP repository '/tools/Xilinx/Vivado/2018.3/data/ip'.
WARNING: [IP_Flow 19-3664] IP 'soc_cpu_wrap_0_0' generated file not found '/home/yutong/RISC-V_SoC/vivado/soc/soc.srcs/sources_1/bd/soc/ip/soc_cpu_wrap_0_0/soc_cpu_wrap_0_0.dcp'. Please regenerate to continue.
WARNING: [IP_Flow 19-3664] IP 'soc_cpu_wrap_0_0' generated file not found '/home/yutong/RISC-V_SoC/vivado/soc/soc.srcs/sources_1/bd/soc/ip/soc_cpu_wrap_0_0/soc_cpu_wrap_0_0_stub.v'. Please regenerate to continue.
WARNING: [IP_Flow 19-3664] IP 'soc_cpu_wrap_0_0' generated file not found '/home/yutong/RISC-V_SoC/vivado/soc/soc.srcs/sources_1/bd/soc/ip/soc_cpu_wrap_0_0/soc_cpu_wrap_0_0_stub.vhdl'. Please regenerate to continue.
WARNING: [IP_Flow 19-3664] IP 'soc_cpu_wrap_0_0' generated file not found '/home/yutong/RISC-V_SoC/vivado/soc/soc.srcs/sources_1/bd/soc/ip/soc_cpu_wrap_0_0/soc_cpu_wrap_0_0_sim_netlist.v'. Please regenerate to continue.
WARNING: [IP_Flow 19-3664] IP 'soc_cpu_wrap_0_0' generated file not found '/home/yutong/RISC-V_SoC/vivado/soc/soc.srcs/sources_1/bd/soc/ip/soc_cpu_wrap_0_0/soc_cpu_wrap_0_0_sim_netlist.vhdl'. Please regenerate to continue.
open_project: Time (s): cpu = 00:00:15 ; elapsed = 00:00:31 . Memory (MB): peak = 6385.043 ; gain = 157.594 ; free physical = 2202 ; free virtual = 8047
update_compile_order -fileset sources_1
reset_run synth_1
reset_run soc_cpu_wrap_0_0_synth_1
WARNING: [Vivado 12-1017] Problems encountered:
1. Attempt to kill process failed

open_bd_design {/home/yutong/RISC-V_SoC/vivado/soc/soc.srcs/sources_1/bd/soc/soc.bd}
Adding cell -- xilinx.com:ip:processing_system7:5.5 - processing_system7_0
Adding cell -- xilinx.com:ip:axi_interconnect:2.1 - axi_interconnect_0
Adding cell -- xilinx.com:ip:axi_protocol_converter:2.1 - auto_pc
Adding cell -- xilinx.com:ip:axi_dwidth_converter:2.1 - auto_us
Adding cell -- xilinx.com:ip:smartconnect:1.0 - smartconnect_0
Adding cell -- xilinx.com:ip:axi_apb_bridge:3.0 - axi_apb_bridge_0
Adding cell -- xilinx.com:ip:proc_sys_reset:5.0 - rst_ps7_0_50M
Adding cell -- user.org:user:cpu_wrap:1.0 - cpu_wrap_0
WARNING: [BD 41-1731] Type mismatch between connected pins: /processing_system7_0/FCLK_CLK1(clk) and /cpu_wrap_0/clk_32k(undef)
Successfully read diagram <soc> from BD file </home/yutong/RISC-V_SoC/vivado/soc/soc.srcs/sources_1/bd/soc/soc.bd>
launch_runs impl_2 -to_step write_bitstream -jobs 2
[Wed May 10 08:46:42 2023] Launched soc_cpu_wrap_0_0_synth_1, synth_1...
Run output will be captured here:
soc_cpu_wrap_0_0_synth_1: /home/yutong/RISC-V_SoC/vivado/soc/soc.runs/soc_cpu_wrap_0_0_synth_1/runme.log
synth_1: /home/yutong/RISC-V_SoC/vivado/soc/soc.runs/synth_1/runme.log
[Wed May 10 08:46:43 2023] Launched impl_2...
Run output will be captured here: /home/yutong/RISC-V_SoC/vivado/soc/soc.runs/impl_2/runme.log
